'use client';

import { ScrollArea } from '@/components/ui/scroll-area';
import { Card } from '@/components/ui/card';
import { AlertTriangle, Shield, FileSearch, Mail } from 'lucide-react';

export default function AboutPage() {
  return (
    <ScrollArea className="h-[calc(100vh-4rem)]">
      <div className="container mx-auto max-w-4xl px-4 py-16">
        <div className="space-y-6">
          {/* Header */}
          <div className="space-y-2 justify-center items-center flex flex-col">
            <h1 className="text-2xl font-semibold">About This Explorer</h1>
            <p className="text-lg text-muted-foreground">
              Understanding the scope, methodology, and limitations of this document corpus
            </p>
          </div>

          {/* What This App Does */}
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">What This App Does</h2>
            <Card className="p-6">
              <div className="space-y-4">
                <p>
                  This application provides a searchable interface for exploring publicly released 
                  documents related to Jeffrey Epstein. Using retrieval-augmented generation (RAG) 
                  technology, it allows users to ask natural language questions and receive answers 
                  grounded in citations from the document corpus.
                </p>
                <p>
                  <strong>Key capabilities:</strong>
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Ask questions in plain English and receive cited answers</li>
                  <li>Browse and search the full document collection</li>
                  <li>View original source documents with page-level navigation</li>
                  <li>Verify every claim against its source material</li>
                  <li>Filter and explore documents by type, date, and topic</li>
                </ul>
              </div>
            </Card>
          </section>

          {/* How Citations Work */}
          <section className="space-y-4">
            <h2 className="text-2xl flex items-center gap-2">
              <FileSearch className="w-6 h-6" />
              How Citations Work
            </h2>
            <Card className="p-6">
              <div className="space-y-4">
                <p>
                  All responses generated by this system include citations that link back to 
                  specific documents and page numbers in the corpus. This allows you to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <strong>Verify sources:</strong> Click any citation to open the original 
                    document at the referenced page
                  </li>
                  <li>
                    <strong>Understand context:</strong> Citations include brief excerpts showing 
                    how the source material relates to the answer
                  </li>
                  <li>
                    <strong>Trace claims:</strong> Every factual statement should be traceable 
                    to one or more source documents
                  </li>
                </ul>
                <div className="bg-muted p-4 rounded-lg mt-4">
                  <p className="text-sm">
                    <strong>Note:</strong> The quality of answers depends on the quality and 
                    completeness of the source documents. Missing pages, OCR errors, or redactions 
                    may affect accuracy.
                  </p>
                </div>
              </div>
            </Card>
          </section>

          {/* Limitations */}
          <section className="space-y-4">
            <h2 className="text-2xl flex items-center gap-2">
              <AlertTriangle className="w-6 h-6" />
              Limitations & Considerations
            </h2>
            <Card className="p-6 border-yellow-500/50 bg-yellow-50/10">
              <div className="space-y-4">
                <p>
                  <strong>This tool has important limitations you should understand:</strong>
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>
                    <strong>OCR Errors:</strong> Documents were converted from scanned images. 
                    Text recognition errors may occur.
                  </li>
                  <li>
                    <strong>Incomplete Records:</strong> Not all documents from legal proceedings 
                    are publicly available. This corpus represents available materials only.
                  </li>
                  <li>
                    <strong>Redactions:</strong> Some documents contain redacted information that 
                    cannot be searched or retrieved.
                  </li>
                  <li>
                    <strong>Context Required:</strong> Documents should be read in full context, 
                    not just as isolated quotes.
                  </li>
                  <li>
                    <strong>Unverified Claims:</strong> The presence of information in court documents 
                    does not automatically mean claims have been proven or verified.
                  </li>
                  <li>
                    <strong>Legal Status:</strong> This is not legal advice. Documents reflect various 
                    stages of legal proceedings with different evidentiary standards.
                  </li>
                </ul>
              </div>
            </Card>
          </section>

          {/* Document Sources */}
          <section className="space-y-4">
            <h2 className="text-2xl">Document Sources</h2>
            <Card className="p-6">
              <p className="mb-4">
                Documents in this corpus were obtained through:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Court-ordered releases in civil and criminal cases</li>
                <li>Freedom of Information Act (FOIA) requests</li>
                <li>Public records requests</li>
                <li>Unsealed court filings</li>
                <li>Government agency disclosures</li>
              </ul>
              <p className="mt-4 text-sm text-muted-foreground">
                All documents in this collection are part of the public record and have been 
                released through official legal channels.
              </p>
            </Card>
          </section>

          {/* Responsible Use */}
          <section className="space-y-4">
            <h2 className="text-2xl flex items-center gap-2">
              <Shield className="w-6 h-6" />
              Responsible Use Guidelines
            </h2>
            <Card className="p-6">
              <div className="space-y-4">
                <p>
                  <strong>When using this tool, please:</strong>
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Verify important claims by reading the full source documents</li>
                  <li>Consider the context and legal status of each document</li>
                  <li>Respect the privacy and dignity of victims and survivors</li>
                  <li>Understand that allegations in legal documents are not the same as proven facts</li>
                  <li>Use this tool for research and education, not harassment or defamation</li>
                  <li>Report any errors or inappropriate content using the report feature</li>
                </ul>
              </div>
            </Card>
          </section>

          {/* Reporting & Feedback */}
          <section className="space-y-4">
            <h2 className="text-2xl flex items-center gap-2">
              <Mail className="w-6 h-6" />
              Reporting & Feedback
            </h2>
            <Card className="p-6">
              <div className="space-y-4">
                <p>
                  We welcome feedback on this tool and its content. You can report:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Inaccurate or inappropriate responses</li>
                  <li>Technical issues or bugs</li>
                  <li>Missing or incorrect document metadata</li>
                  <li>Suggestions for improvement</li>
                </ul>
                <p className="text-sm text-muted-foreground mt-4">
                  Use the &quot;Report&quot; button on any response to flag content for review. 
                  Your feedback helps improve the quality and accuracy of this tool.
                </p>
              </div>
            </Card>
          </section>

          {/* Disclaimer */}
          <Card className="p-6 border-destructive/50 bg-destructive/5">
            <div className="space-y-2">
              <h3 className="font-semibold">Disclaimer</h3>
              <p className="text-sm">
                This is a research and educational tool. The information provided is derived from 
                publicly available court documents and legal filings. It should not be considered 
                legal advice, verified fact, or a complete record of events. Users should independently 
                verify information and consult qualified professionals for legal matters. The creators 
                of this tool make no warranties about the accuracy, completeness, or currency of the 
                information provided.
              </p>
            </div>
          </Card>
        </div>
      </div>
    </ScrollArea>
  );
}